### ISSUE TITLE
Install / server startup issue 

### ISSUE THREAD

**Issue by stevesoto** [thrasr/mdm-server#14]
Installed per instructions. First time running 
root@mdm3:/home/mdm/mdm-server/server# python server.py
Traceback (most recent call last):
  File "server.py", line 5, in <module>
    from APNSWrapper import *
ImportError: No module named APNSWrapper

So, I installed APNSWrapper. That problem solved.

Second time starting the server....

root@mdm3:/home/mdm/mdm-server/server# python server.py
Traceback (most recent call last):
  File "server.py", line 57, in <module>
    x509 = X509.load_cert('identity.crt')
  File "/usr/lib/python2.7/dist-packages/M2Crypto/X509.py", line 609, in load_cert
    bio = BIO.openfile(file)
  File "/usr/lib/python2.7/dist-packages/M2Crypto/BIO.py", line 186, in openfile
    return File(open(filename, mode))
IOError: [Errno 2] No such file or directory: 'identity.crt'
root@mdm3:/home/mdm/mdm-server/server# ls
CA.crt      Enroll.mobileconfig   Identity.p12             problems.py   Server.crt  static
device.py   Example.mobileconfig  LICENSE                  problems.pyc  Server.key  xactn.log
device.pyc  favicon.ico           Manifest.plist.template  README        server.py

Thoughts? Is it as simple as a file rename?

**Comment by stevesoto** [comment]
I just copied the required file from the ./home/mdm/mdm-server/scripts/identity.crt location to the ./home/mdm/mdm-server/server location and the server started. You can close this. -Steve

**Comment by thrasr** [comment]
I'll make sure indentity.crt gets moved to the proper location in the original setup script.  Thanks.
